### ISSUE TITLE
XSS flux is not working

### ISSUE THREAD

**Issue by edimitchel** [antfu/releases.antfu.me#3]
### Describe the bug

The XSS flux is not rendering well.

### Reproduction

https://releases.antfu.me/feed.xml

### System Info

```Shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
What do you mean, and what do you suggest?

**Comment by edimitchel** [comment]
The content on my side is not showing anything. I expect to have same content shown on the website but formatted in XSS XML format.

<img width="413" alt="Capture d’écran 2024-08-21 à 09 25 12" src="https://github.com/user-attachments/assets/f275ab21-a25c-47b3-a8ef-150e5976715b">

**Comment by antfu** [comment]
<img width="773" alt="Screenshot 2024-08-21 at 13 46 23" src="https://github.com/user-attachments/assets/32662f8a-5647-4797-84b6-0d560f0d7f13">

Seems to work fine for me, tried both Chrome and Firefox

**Comment by edimitchel** [comment]
Hoo my bad, my browser was interpreting the xml, by looking the source, it's ok.

Sorry ;)
